<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>Exe</OutputType>
	  <TargetFramework>net472</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <PlatformTarget>AnyCPU</PlatformTarget>
	  <Prefer32Bit>false</Prefer32Bit>
	  <Nullable>enable</Nullable>
	  <Configurations>Debug;Release;微软;微软测试;微软联调</Configurations>
	  <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == '微软' Or '$(Configuration)' == '微软测试' Or '$(Configuration)' == '微软联调'">
	  <DefineConstants>$(DefineConstants);MICROSOFTSTORE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
	  <EasyHookManagedPath Condition="'$(Configuration)' == '微软' Or '$(Configuration)' == '微软测试' Or '$(Configuration)' == '微软联调'">..\ThirdParty\EasyHook\lib\net40-msix\EasyHook.dll</EasyHookManagedPath>
	  <EasyHookManagedPath Condition="'$(EasyHookManagedPath)' == ''">..\ThirdParty\EasyHook\lib\net40\EasyHook.dll</EasyHookManagedPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QQMusicDecryptHook\QQMusicDecryptHook.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EasyHook">
      <HintPath>$(EasyHookManagedPath)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
